name: Deploy Multihop_RAG
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests

      - name: Run API
        run: python modules/api/api_endpoints.py

      - name: Evaluate model
        run: python evaluation/evaluate.py

